name: Push Build to Artifactory

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ secrets.ARTIFACTORY_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

    - name: Upload to Artifactory
      run: |
        echo "test file" > test.txt
        export BUILD_NAME="my-build"
        export BUILD_MODULE="my-module"
        export BUILD_NUMBER="1"
        export PATH_TO_DIRECTORY="name/version/dates"
      
        jfrog rt upload "test.txt" example-repo-local/$PATH_TO_DIRECTORY --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE

    - name: Publish Build Info and Delete Older Builds
      run: |
        export BUILD_NAME="my-build"
        export BUILD_NUMBER="1"
        
        # Publish build information to Artifactory
        jfrog rt build-publish $BUILD_NAME $BUILD_NUMBER
        
        # Delete older builds, keeping only the latest
        jfrog rt bdi delete $BUILD_NAME --max-builds=1
